apiVersion: v1
kind: Pod
metadata:
  name: init-container
  namespace: demo
  labels:
    app: init-container
spec:
  containers:
  - name: my-app
    image: nginx:1.17.1
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
      - name: workdir
        mountPath: /usr/share/nginx/html
  initContainers:
    - name: my-init-app
      image: busybox:1.28
      command:
      - wget
      - "-O"
      - "/work-dir/index.html"
      - "https://www.baidu.com"
      volumeMounts:
       - name:  workdir
         mountPath:  /work-dir
  volumes:
    - name: workdir
      emptyDir: {}